"""initial schema

Revision ID: cf91e49678e2
Revises:
Create Date: 2025-12-24 01:53:34.965588

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf91e49678e2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("biography", sa.String(length=250), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("authors_pkey")),
    )
    op.create_index(
        op.f("ix_authors_created_at"), "authors", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_authors_deleted_at"), "authors", ["deleted_at"], unique=False
    )
    op.create_table(
        "genres",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("genres_pkey")),
    )
    op.create_index(
        op.f("ix_genres_created_at"), "genres", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_genres_deleted_at"), "genres", ["deleted_at"], unique=False
    )
    op.create_table(
        "publishers",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("contact_number", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("publishers_pkey")),
    )
    op.create_index(
        op.f("ix_publishers_created_at"), "publishers", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_publishers_deleted_at"), "publishers", ["deleted_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=15), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint("email", name=op.f("users_email_key")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_table(
        "books",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("publisher_year", sa.Integer(), nullable=False),
        sa.Column("publisher_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["publisher_id"],
            ["publishers.id"],
            name=op.f("books_publisher_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("books_pkey")),
    )
    op.create_index(op.f("ix_books_created_at"), "books", ["created_at"], unique=False)
    op.create_index(op.f("ix_books_deleted_at"), "books", ["deleted_at"], unique=False)
    op.create_table(
        "author_books",
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
            name=op.f("author_books_author_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
            name=op.f("author_books_book_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("author_id", "book_id", name=op.f("author_books_pkey")),
    )
    op.create_index(
        op.f("ix_author_books_created_at"), "author_books", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_author_books_deleted_at"), "author_books", ["deleted_at"], unique=False
    )
    op.create_table(
        "borrowings",
        sa.Column("borrow_date", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("return_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("due_date", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("BORROWED", "RETURNED", "OVERDUE", name="borrow_status"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
            name=op.f("borrowings_book_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("borrowings_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("borrowings_pkey")),
    )
    op.create_index(
        op.f("ix_borrowings_created_at"), "borrowings", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_borrowings_deleted_at"), "borrowings", ["deleted_at"], unique=False
    )
    op.create_table(
        "genre_books",
        sa.Column("genre_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
            name=op.f("genre_books_book_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
            name=op.f("genre_books_genre_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("genre_id", "book_id", name=op.f("genre_books_pkey")),
    )
    op.create_index(
        op.f("ix_genre_books_created_at"), "genre_books", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_genre_books_deleted_at"), "genre_books", ["deleted_at"], unique=False
    )
    op.create_table(
        "inventories",
        sa.Column("shelf_location", sa.String(length=100), nullable=False),
        sa.Column("total_quantity", sa.Integer(), nullable=False),
        sa.Column("available_quantity", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
            name=op.f("inventories_book_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("inventories_pkey")),
    )
    op.create_index(
        op.f("ix_inventories_created_at"), "inventories", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_inventories_deleted_at"), "inventories", ["deleted_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventories_deleted_at"), table_name="inventories")
    op.drop_index(op.f("ix_inventories_created_at"), table_name="inventories")
    op.drop_table("inventories")
    op.drop_index(op.f("ix_genre_books_deleted_at"), table_name="genre_books")
    op.drop_index(op.f("ix_genre_books_created_at"), table_name="genre_books")
    op.drop_table("genre_books")
    op.drop_index(op.f("ix_borrowings_deleted_at"), table_name="borrowings")
    op.drop_index(op.f("ix_borrowings_created_at"), table_name="borrowings")
    op.drop_table("borrowings")
    op.drop_index(op.f("ix_author_books_deleted_at"), table_name="author_books")
    op.drop_index(op.f("ix_author_books_created_at"), table_name="author_books")
    op.drop_table("author_books")
    op.drop_index(op.f("ix_books_deleted_at"), table_name="books")
    op.drop_index(op.f("ix_books_created_at"), table_name="books")
    op.drop_table("books")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_publishers_deleted_at"), table_name="publishers")
    op.drop_index(op.f("ix_publishers_created_at"), table_name="publishers")
    op.drop_table("publishers")
    op.drop_index(op.f("ix_genres_deleted_at"), table_name="genres")
    op.drop_index(op.f("ix_genres_created_at"), table_name="genres")
    op.drop_table("genres")
    op.drop_index(op.f("ix_authors_deleted_at"), table_name="authors")
    op.drop_index(op.f("ix_authors_created_at"), table_name="authors")
    op.drop_table("authors")

    sa.Enum(name="borrow_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
